### ISSUE TITLE
Doesn't work well with cache plugins

### ISSUE THREAD

**Issue by Raboo** [bleutzinn/grav-plugin-editable#3]
Hi,

I tried using editable with both AdvancedPageCache and PreCache enabled.

First off, the "Edit me" button doesn't appear if I don't clear all the cache after I login.
Second, it is unable to save changes, could be due the the cache plugins as well.

**Comment by bleutzinn** [comment]
Unfortunately, as stated in the ReadMe, the plugin can not be used with caching enabled.

The problem is that Grav needs to deliver different content: the normal page for anonymous visitors and a modified version of that page to logged in users. The modified version contains the Edit button etc.

The cache does not distinguish the visitor from the logged in user and simply serves the page which is stored in the cache.
This is where things go wrong. When the cache contains the normal page, the logged in users gets that page which has no Edit button. Visa versa, when the user is logged in and you clear the cache, chances are that the logged in version gets cached and thus will also be presented to not logged in users or visitors.

**Comment by Raboo** [comment]
True, it says it doesn't work with cache enabled.
So no workaround in sight?

**Comment by bleutzinn** [comment]
Making Editable work with caching enabled has been high on my to do list from the beginning of the plugin.

I now have a working version of Editable with the SimpleMDE add-on which works with the Grav core caching, the PreCache Plugin and the AdvancedPageCache Plugin. This version is still in a very raw state and not ready to be released. Also changes affect the ContentTools add-on as well.

If you want to test I can create a quick working copy of my test site. Let me know.

**Comment by Raboo** [comment]
Sure I can test it if you want, haven't really gotten started with my blog yet, so it doesn't matter if I brick it.

**Comment by bleutzinn** [comment]
Please take this [Gist](https://gist.github.com/bleutzinn/4fce1dc80efcaed23bc218583e49b4d4) to replace the original editable.php file. It should allow you to edit page content and blog posts in the front-end with caching enabled.
Note that this modification only works with the SimpleMDE as the front-end editor.

Let me know whether or not it works for you.

**Comment by Raboo** [comment]
Hi, it doesn't work.
Basically I edit the page, press save (nothing really happens when I press save), I press close. The page displays my changes. But this is only my view. Open up a new incognito window, and it's the pre-edited view. And in the admin interface, editing the page it don't have my changes. So that change aren't really saved anywhere.

**Comment by bleutzinn** [comment]
I updated the SimpleMDE demo site which has caching enabled. You can download the entire site including the Editable Plugin with a modified SimpleMDE Editor Add-on plus configuration from [there](https://wardenier.eu/simplemde-demo/).

That demo/site doesn't use the PreCache Plugin and the AdvancedPageCache Plugin but they should work also.

**Comment by Raboo** [comment]
I have more info on why it didn't work for me
`Call to undefined method Grav\Plugin\EditablePlugin::setErrorCode()`
file: /srv/users/serverpilot/apps/something/public/user/plugins/editable/editable.php
line 131

**Comment by bleutzinn** [comment]
Normally only existing pages can be edited so yours is a rare situation. However the error pointed to the fact that the error 404 was not handled properly. I fixed that and placed a new download file on the demo site homepage.
Note that the 404 will only be visible in the browser console so when you don't get a green 'Checked' icon upon a save that is where to look.

**Comment by Raboo** [comment]
So I should copy the editable plugin from the demo site onto my user/plugin directory?
Or just install the demo site and add all my plugins and stuff to see if it works?

**Comment by bleutzinn** [comment]
I suggest to download the demo site. Test it. Then if it works for you add your own content from user/pages. Test again. If OK add plugins and check again.
If all goes well you could then return to your original site and install the plugin from the demo site.
One way or the other depends on how complex your own site is.

**Comment by Raboo** [comment]
Your site still don't work for me, getting a 404 when i try to save.
test for yourself http://something.fail/edit/demo-md-1

**Comment by bleutzinn** [comment]
Might well be related to https://github.com/bleutzinn/grav-plugin-editable/issues/5

**Comment by bleutzinn** [comment]
Closing for now.
